//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDenemeForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_kullanıcı
    {
        public int kullanıcıID { get; set; }
        public string kullanıcıAd { get; set; }
        public string kullanıcıSoyad { get; set; }
        public string kullanıcıSifre { get; set; }
        public string kullanıcıEmail { get; set; }
    }
}
